import './globals.css';
import React from 'react';
import { Header, Footer } from '@/app/components/Layout';

import { Roboto_Flex } from 'next/font/google';

const roboto = Roboto_Flex({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const bodyStyle = "min-h-screen flex flex-col items-center gap-6 md:gap-8 lg:gap-10 xl:gap-14 bg-primary-dark text-white";
const mainStyle = "w-full grow mt-20 py-8 lg:py-16 flex flex-col items-center gap-6 xl:px-6 md:gap-8 lg:gap-10 xl:gap-14";

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="fr" className={roboto.className}>
      <body 
        className={`${bodyStyle}`}
        >
        <Header/>
        <main className={`${mainStyle}`}>
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
};

export default RootLayout;
