import './globals.css';
import React from 'react';
import { Header, Footer } from '@/app/components/Layout';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={"flex min-h-screen flex-col items-center justify-between p-24"}>
        <Header/>
          {children}
        <Footer/>
      </body>
    </html>
  );
};

export default RootLayout;
